Traceback (most recent call last):
  File "test.py", line 18, in <module>
    obj.get()
  File "test.py", line 7, in get
    self.func_name()
AttributeError: 'MyClass' object has no attribute 'func_name'